remote_theme: 'okpine/theme'
title: okpine
description: welcome
encoding: "utf-8"
timezone: "Asia/Shanghai"
lang: "zh-CN"
url: "https://www.okpine.com"

defaults            :
  -
   scope:
     path: "" # an empty string here means all files in the project
   values:
     layout: "default"
     author: "wangjing<uni.wangjing@gmail.com>"
